# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    indexes:
       app:
           finder: ~
           settings:
               index:
                   analysis:
                       analyzer:
                           name_analyzer:
                               type: custom
                               tokenizer: standard
                               filter: [lowercase, asciifolding, elision]
           types:
               product:
                    properties:
                        name: ~
                        unitPrice: ~
                        discount: ~
                        categories:
                            type: "nested"
                            properties:
                                title:
                                    type: keyword
#                                    index: not_analyzed
                        attributeValues:
                            type: "nested"
                            properties:
                                value: ~
                                attributeType:
                                    type: "nested"
                                    properties:
#                                      index: not_analyzed
                                        name:
                                            type: keyword
#                                    type: text
#                                    index: not_analyzed
                    persistence:
                        driver: orm
                        model: App\Entity\Product
                        provider: ~
                        listener: ~
                        finder: ~