# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    indexes:
        product:
               properties:
                   final_price:
                       type: float
                   categories:
                       type: "nested"
                       properties:
                           id:
                               type: integer
                   attributeValues:
                       type: "nested"
                       properties:
                           attributeType:
                               type: keyword
                           value:
                               type: keyword
                           product:
                               type: keyword

               persistence:
                   driver: orm
                   model: App\Entity\Product
                   provider: ~
                   listener: ~
                   finder: ~