framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    #http_method_override: true
#    translator: { fallbacks: ['%locale%'] }
    error_controller: App\Controller\CatalogController::errorPageActive
    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
#        handler_id: session.handler.native_file
#        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        cookie_secure: auto
        cookie_samesite: lax
        cookie_lifetime: 604800 # 1 week in seconds 604800 //2592000 - 30 days in seconds

    #esi: true
    #fragments: true
    php_errors:
        log: true
