# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    # configure resolvers
    resolvers :
        # setup the default resolver
        default :
            # use the default web path
            web_path : ~
    loaders:
        default:
            filesystem:
                data_root: "%kernel.project_dir%/"
    # your filter sets are defined here
    filter_sets :
        # use the default cache configuration
        cache : ~
        # the name of the "filter set"
#        thumb_product :
            # adjust the image quality to 75%
#            quality : 95
            # list of transformations to apply (the "filters")
#            filters :
                # create a thumbnail: set size to 120x90 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
#                thumbnail  : { size : [320, 200], mode : outbound }

                # create a 2px black border: center the thumbnail on a black background
                # 4px larger to create a 2px border around the final image
#                background : { size : [324, 204], position : center, color : '#000000' }

#        thumb_product_info :
#            quality : 95
#            filters :
#                thumbnail  : { size : [500, 350], mode : outbound }

        # keep this other delete
        cart_univers2 :
            quality : 95
            filters :
                thumbnail  : { size : [320, 220], mode : outbound }

