sonata_admin:
    title: 'Craft Bud'
    title_logo: 'favicon.ico'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: center, class: col-md-8 }
    global_search:
        empty_boxes: hide


sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
