vich_uploader:
    db_driver: orm

    mappings:
        products:
            uri_prefix: /media/cache/cart_univers2/assets/images/products
            upload_destination: '%kernel.project_dir%/assets/images/products'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        images:
            uri_prefix: /media/cache/cart_univers2/assets/images/products
            upload_destination: '%kernel.project_dir%/assets/images/products'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        category:
            uri_prefix: /media/cache/cart_univers2/assets/images/products
            upload_destination: '%kernel.project_dir%/assets/images/products'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true